//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHotel.Clients.Core {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartHotel.Clients.Core.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Eco Mode.
        /// </summary>
        internal static string ActivateEcoMode {
            get {
                return ResourceManager.GetString("ActivateEcoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient Light.
        /// </summary>
        internal static string AmbientLight {
            get {
                return ResourceManager.GetString("AmbientLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient settings.
        /// </summary>
        internal static string AmbientSettings {
            get {
                return ResourceManager.GetString("AmbientSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be green.
        /// </summary>
        internal static string BeGreen {
            get {
                return ResourceManager.GetString("BeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK A CONFERENCE ROOM.
        /// </summary>
        internal static string BookConferenceMayus {
            get {
                return ResourceManager.GetString("BookConferenceMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK A ROOM.
        /// </summary>
        internal static string BookMayus {
            get {
                return ResourceManager.GetString("BookMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch Bot..
        /// </summary>
        internal static string BotError {
            get {
                return ResourceManager.GetString("BotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select which messenger app would you like to use.
        /// </summary>
        internal static string BotSelectionMessage {
            get {
                return ResourceManager.GetString("BotSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot selection.
        /// </summary>
        internal static string BotSelectionTitle {
            get {
                return ResourceManager.GetString("BotSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in/out.
        /// </summary>
        internal static string CheckInOut {
            get {
                return ResourceManager.GetString("CheckInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out.
        /// </summary>
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        internal static string Coming {
            get {
                return ResourceManager.GetString("Coming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Room.
        /// </summary>
        internal static string ConferenceRoom {
            get {
                return ResourceManager.GetString("ConferenceRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current JSON file URL:.
        /// </summary>
        internal static string CurrentJson {
            get {
                return ResourceManager.GetString("CurrentJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Eco Mode.
        /// </summary>
        internal static string DeactivateEcoMode {
            get {
                return ResourceManager.GetString("DeactivateEcoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to book a room in {0}?.
        /// </summary>
        internal static string DialogBookingMessage {
            get {
                return ResourceManager.GetString("DialogBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        internal static string DialogBookingTitle {
            get {
                return ResourceManager.GetString("DialogBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DialogNo {
            get {
                return ResourceManager.GetString("DialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string DialogOk {
            get {
                return ResourceManager.GetString("DialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DialogYes {
            get {
                return ResourceManager.GetString("DialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do today?.
        /// </summary>
        internal static string DoToday {
            get {
                return ResourceManager.GetString("DoToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Room.
        /// </summary>
        internal static string DoubleRoom {
            get {
                return ResourceManager.GetString("DoubleRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to eat today?.
        /// </summary>
        internal static string EatToday {
            get {
                return ResourceManager.GetString("EatToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only B2C users can book a room..
        /// </summary>
        internal static string ExceptionB2CMessage {
            get {
                return ResourceManager.GetString("ExceptionB2CMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred, try again.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ExceptionTitle {
            get {
                return ResourceManager.GetString("ExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find my room.
        /// </summary>
        internal static string FindRoom {
            get {
                return ResourceManager.GetString("FindRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO TO MY ROOM.
        /// </summary>
        internal static string GoMyRoomMayus {
            get {
                return ResourceManager.GetString("GoMyRoomMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupancy on selected dates is very high. Complete your booking as soon as possible!..
        /// </summary>
        internal static string HighOccupancy {
            get {
                return ResourceManager.GetString("HighOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication error: {0}.
        /// </summary>
        internal static string HttpRequestExceptionMessage {
            get {
                return ResourceManager.GetString("HttpRequestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string HttpRequestExceptionTitle {
            get {
                return ResourceManager.GetString("HttpRequestExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Room.
        /// </summary>
        internal static string IndividualRoom {
            get {
                return ResourceManager.GetString("IndividualRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from JSON.
        /// </summary>
        internal static string LoadJson {
            get {
                return ResourceManager.GetString("LoadJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High availability on select dates..
        /// </summary>
        internal static string LowOccupancy {
            get {
                return ResourceManager.GetString("LowOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation on selected dates is considerable. Keep that in mind..
        /// </summary>
        internal static string MediumOccupancy {
            get {
                return ResourceManager.GetString("MediumOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music volume.
        /// </summary>
        internal static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAKE A NEW BOOKING.
        /// </summary>
        internal static string NewBookingMayus {
            get {
                return ResourceManager.GetString("NewBookingMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        internal static string NextMayus {
            get {
                return ResourceManager.GetString("NextMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please bring your device to.
        /// </summary>
        internal static string NfcMessage01 {
            get {
                return ResourceManager.GetString("NfcMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the NFC card area..
        /// </summary>
        internal static string NfcMessage02 {
            get {
                return ResourceManager.GetString("NfcMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC not available.
        /// </summary>
        internal static string NoNfc {
            get {
                return ResourceManager.GetString("NoNfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications.
        /// </summary>
        internal static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented.
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open door.
        /// </summary>
        internal static string OpenDoor {
            get {
                return ResourceManager.GetString("OpenDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote JSON file URL.
        /// </summary>
        internal static string RemoteJson {
            get {
                return ResourceManager.GetString("RemoteJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room temperature.
        /// </summary>
        internal static string RoomTemperature {
            get {
                return ResourceManager.GetString("RoomTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all +.
        /// </summary>
        internal static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope to see you again.
        /// </summary>
        internal static string SeeYou {
            get {
                return ResourceManager.GetString("SeeYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string SignInMayus {
            get {
                return ResourceManager.GetString("SignInMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN WITH MICROSOFT ACCOUNT.
        /// </summary>
        internal static string SignInMicrosoftMayus {
            get {
                return ResourceManager.GetString("SignInMicrosoftMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        internal static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hotel.
        /// </summary>
        internal static string TheHotel {
            get {
                return ResourceManager.GetString("TheHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        internal static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window blinds.
        /// </summary>
        internal static string WindowBlinds {
            get {
                return ResourceManager.GetString("WindowBlinds", resourceCulture);
            }
        }
    }
}
